server.port: 8082

spring:
    data.mongodb.uri: mongodb://localhost:27017/orderly

    messages:
        basename: i18n/messages
        cache-seconds: -1
        encoding: UTF-8
        
orderly.security.xauth.secret: qwerty
        
logging:
    level: 
        org:
            springframework:
                web:
                    client:
                        RestTemplate: DEBUG
        

        
management:
    contextPath: /manage

